generators:
# Blueprint demo yamls
- blueprint/demo/operators.yaml
- blueprint/demo/site.yaml
- blueprint/global/mcp-w-dell-650-i.yaml
- blueprint/global/mcp-w-dell-750-i.yaml
- blueprint/global/mcp-w-dell-750-m.yaml
- blueprint/global/validator-mcp-w-dell-650-i.yaml
- blueprint/global/validator-mcp-w-dell-750-i.yaml
- blueprint/global/validator-mcp-w-dell-750-m.yaml
- blueprint/global/validator-sriov.yaml
#
# Cluster demo
- cluster/demo/demo.yaml
- cluster/demo/onboard.yaml

resources:
- ns.yaml
