apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding name as {name}-placementBinding, the placementRule name as {name}-placementRule,
  # and the policy name as {name}-{spec.sourceFiles[x].policyName}
  name: "bp-global-validator-sriov"
  namespace: "ztp-group"
spec:
  # This policy will correspond to all clusters with label specified in bindingRules and
  # without label specified in bindingExcludedRules.
  bindingRules:
    sriov: "true"
  bindingExcludedRules:
    # The ztp-done label is used in coordination with the Topology Aware Lifecycle Operator(TALO).
    # Please do not change this label.
    ztp-done: ""
  sourceFiles:
    # Create inform policy to validate configuration CRs that will be applied to all 3-node clusters
    - fileName: validatorCRs/informSriovValidator.yaml
      remediationAction: inform
      policyName: "sriov-policy"
      # This low setting is only valid if the validation policy is disconnected from the cluster at steady-state
      # using a bindingExcludeRules entry with ztp-done
      evaluationInterval:
        compliant: 5s
