apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
## Helm chart demo for 3xM and 5xW with ODF
#- demo-yaml
## Kustomize demo for 3xM and 5xW with ODF
#- ztp/demo.yaml
## Kustomize demo for 3xM and 2xW without ODF
- ztp/demo2.yaml

resources:
- ztp/demo-secrets.yaml

