---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "bp-demo-site"
  namespace: "ztp-group"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    blueprint-demo: "true"
  sourceFiles:
    # Create policies that will be installed only in a specific cluster

    # Set label selection for sr-iov
    #
    - fileName: SriovOperatorConfig-label.yaml
      policyName: "design"
    #
    # Move Ingress router to Masters (BM)
    #
    #- fileName: master-ingress-router.yaml
    #  policyName: "mno-config-policy"
    #  complianceType: musthave
    #
    # Enable log forwarding to kafka
    #
    #- fileName: LOG/ClusterLogForwarder.yaml
    #  policyName: "log-forwarder"
    #  spec:
    #    outputs:
    #       - name: infra-logs
    #         type: kafka
    #         url: tls://mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.tmetse.bos2.lab:443/nec-site-infra-logs
    #         secret:
    #           name: kafka-secret
    #       - name: audit-logs
    #         type: kafka
    #         url: tls://mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.tmetse.bos2.lab:443/nec-site-audit-logs
    #         secret:
    #           name: kafka-secret
    #       - name: app-logs
    #         type: kafka
    #         url: tls://mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.tmetse.bos2.lab:443/nec-site-app-logs
    #         secret:
    #           name: kafka-secret
    #    pipelines:
    #      - name: nec-site-infra-logs
    #        inputRefs:
    #        - infrastructure
    #        outputRefs:
    #        - infra-logs
    #        labels:
    #          logType: "infra"
    #      - name: nec-site-audit-logs
    #        inputRefs:
    #        - audit
    #        outputRefs:
    #        - audit-logs
    #        labels:
    #          logType: "audit"
    #      - name: nec-site-app-logs
    #        inputRefs:
    #        - application
    #        outputRefs:
    #        - app-logs
    #        labels:
    #          logType: "app"
    #
    # Deploy Prometheus Kafka Adapter
    #
    #- fileName: MON/kafkaAdapDeployment.yaml
    #  policyName: "dply-prom-kafka-adapter"
    #  spec:
    #    template:
    #      spec:
    #        containers:
    #        - env:
    #          - name: KAFKA_BROKER_LIST
    #            value: mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.tmetse.bos2.lab:443
    #          - name: KAFKA_TOPIC
    #            value: nec-site-ocp-metrics
