apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-operator-group
  namespace: openshift-local-storage
  annotations:
    ran.openshift.io/ztp-deploy-wave: "5"
spec:
  targetNamespaces:
    - openshift-local-storage
---

