apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
  annotations:
    ran.openshift.io/ztp-deploy-wave: "5"
spec:
  channel: "4.12"
  installPlanApproval: Manual
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
